### ISSUE TITLE
More freedom around freebies

### ISSUE THREAD

**Issue by DrSharky** [DrSharky/VTMsite#179]
Submitter: Luciano P.
It would be interesting to be able to allow for more freebies to be spent (for Elder chronicles, for example). It could take the form of either allowing the number of freebies allowed manually or (better yet) a mode where instead of depleting the available freebies, the counter on the top would start at 0 and then just sum all of the spent freebies to show how many were spent already.

**Comment by cobrabr** [comment]
I'm the original submitter of the suggestion above, and I just realized what I wrote is somewhat confusing. Let me clarify.

Right now, we only get to spend 15 freebies, which is the default, but it's somewhat restrictive, given how many alternative character creation rules exist (even within the official WW books themselves). Some rules suggest 21 or even 35 freebies for Elders, and there are character creation rules in which everything is converted to freebies. It would be nice to be able to use this tool (which is by far the best one I've ever seen for VtM) in those scenarios.

I realize some of these alternative creation rules would entail a lot of work to be made available, but addressing the lower-hanging fruit (i.e. the hard-coded fixed number of freebies) by allowing more freedom in that regard might be enough for most people (certainly so for me 😄). My suggestions on how to implement this are to either 1) allow the max number of freebies to be changed (e.g. a button beside the big red "15" on the top-right corner of the screen to allow changing that value) or 2) to create a mode in which there is no max limit, where the freebie counter would instead add all spent freebies and show the total (this would put the responsibility of verifying how many points are spent on the user, which is a fine trade-off). This last option would have the added benefit of allowing Storytellers to build their NPCs in the tool, since we obviously don't follow the stricter PC creation rules for NPCs.

**Comment by DrSharky** [comment]
Sorry for the late reply, I've been busy, and honestly I forgot that I hadn't replied to this one.
I have received requests for a format that provides more freedom. In fact I think this is the most highly requested feature. It pretty much puts it at the top of the list, probably even above the layout overhaul (because redoing the layout will take forever).

The trouble is, as you mentioned, different ways to do it, and the best way is not easy to determine. From my experience working on this, I think the latter option of creating a separate page or option for the (let's call it storyteller mode) would be the best approach. I could be wrong, but that's my initial reaction. I haven't worked on this project in some time unfortunately. I'd love to dedicate more time to it, but haven't had the opportunity.

I'll keep this issue open, it's basically a dupe, but also the most well thought-out suggestion, and if you're watching this one, it'll update and you can see when progress happens. Besides, the issues list isn't so busy that dupes really have a negative effect anyways.

**Comment by cobrabr** [comment]
No worries @DrSharky, I unfortunately know all about being too busy to work on stuff we want to (vs. on what we _have_ to). I actually wish I had the time to put in a PR myself (I don't know much about Angular itself, but that would be a small hurdle), but I don't, either.

I like the idea of a "Storyteller mode", and I do think it's probably the best idea, as it allows you to introduce more changes/differences if you want to in the future. It is more work, though, so I'd be fine with a simpler solution. 

Let me know if there's anything I can help with. If it's a smaller piece, I can probably find some smaller chunk of time to try my hand at it.

Cheers!
